Failure # 1 (occurred at 2023-09-28_00-36-59)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=16223, ip=172.17.137.197, actor_id=1399a11204ee5e5dac77c2f701000000, repr=PPO)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 227, in _setup
    self.add_workers(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 593, in add_workers
    raise result.get()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/actor_manager.py", line 481, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=16390, ip=172.17.137.197, actor_id=b8f38fd4162b2fd62ae6208501000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fb5107b4b80>)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 525, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 1727, in _update_policy_map
    self._build_policy_map(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 1838, in _build_policy_map
    new_policy = create_policy_for_framework(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/utils/policy.py", line 142, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 49, in __init__
    TorchPolicyV2.__init__(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/policy/torch_policy_v2.py", line 92, in __init__
    model = self.make_rl_module()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/policy/policy.py", line 424, in make_rl_module
    marl_module = marl_spec.build()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/marl_module.py", line 462, in build
    module = self.marl_module_class(module_config)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/rl_module.py", line 377, in new_init
    previous_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/rl_module.py", line 377, in new_init
    previous_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/marl_module.py", line 58, in __init__
    super().__init__(config or MultiAgentRLModuleConfig())
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/rl_module.py", line 369, in __init__
    self.setup()
  File "/home/dylan/projects/lang-acq/jtc/macrl/simple_macrl.py", line 99, in setup
    super().setup()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/marl_module.py", line 65, in setup
    self._rl_modules[module_id] = module_spec.build()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/rl_module.py", line 104, in build
    module = self.module_class(module_config)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/rl_module.py", line 377, in new_init
    previous_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/rl_module.py", line 377, in new_init
    previous_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/torch/torch_rl_module.py", line 82, in __init__
    RLModule.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/core/rl_module/rl_module.py", line 369, in __init__
    self.setup()
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/algorithms/ppo/ppo_rl_module.py", line 23, in setup
    self.encoder = catalog.build_actor_critic_encoder(framework=self.framework)
  File "/home/dylan/projects/lang-acq/jtc/macrl/macrl_catalog.py", line 103, in build_actor_critic_encoder
    return self._get_model(
  File "/home/dylan/projects/lang-acq/jtc/macrl/macrl_catalog.py", line 82, in _get_model
    if self.share_agent_params:
  File "/home/dylan/projects/lang-acq/jtc/macrl/macrl_catalog.py", line 77, in share_agent_params
    return self._model_config_dict['share_agent_params']
KeyError: 'share_agent_params'

During handling of the above exception, another exception occurred:

[36mray::PPO.__init__()[39m (pid=16223, ip=172.17.137.197, actor_id=1399a11204ee5e5dac77c2f701000000, repr=PPO)
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/algorithms/algorithm.py", line 517, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/ray/tune/trainable/trainable.py", line 185, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/algorithms/algorithm.py", line 639, in setup
    self.workers = WorkerSet(
  File "/usr/local/lib/python3.10/dist-packages/ray/rllib/evaluation/worker_set.py", line 179, in __init__
    raise e.args[0].args[2]
KeyError: 'share_agent_params'
